### ISSUE TITLE
Add support for customised css?

### ISSUE THREAD

**Issue by fraserxu** [freeman-lab/minidocs#1]
Hi, do you have any plan for supporting inject customised css? The reason is that while building a documentation for a team, there's high chance that will need to follow some sort of branding, colour schema etc.

Do you think we can add an option to the api that support custom CSS?

### Usage

```JavaScript
require('minidocs')(contents, {
  logo: 'logo.svg',
  style: 'style.css'
})
```

### And the code

```JavaScript
var customCss = fs.readFileSync(path.join(__dirname, opts.style))
insertcss(customCss)
```

Please let me know what you think and I'm happy to create a pull request for it, thanks!

**Comment by freeman-lab** [comment]
@fraserxu nice idea! It'd be great to support this, only tricky thing is that when bundling with `browserify` and `brfs` the argument to `readFileSync` needs to be statistically analyzable, so no variables (see [here](https://github.com/substack/brfs#gotchas)).

One workaround could be to make the option a boolean, and then if `style: true` assume there's a file present called `style.css`, and read it and insert it. Slightly awkward, but it should work, and it's also how we're specifying the `markdown` folder for now.

Would that work for what you had in mind? Or maybe you have other ideas? In either case, a PR would definitely be welcome!

When we add a `minidocs` command line tool it can offer more sophisticated file naming options because it'll be doing the bundling itself, but this version I think requires some hardcoding.

**Comment by fraserxu** [comment]
Yes, I realised this when trying to implement it on my local.

I have a simple demo working on my local that read the boolean value of `opts.theme` or `opts.style`, if it's there then insert the css named `theme.css` into the page.

I think it could work at this stage. 

:+1:  that it could be improved once there's a cli tool.
